load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "protobuf_mutator_lib",
    srcs = [
        "src/mutator.cc",
    ],
    hdrs = [
        "src/mutator.h",
        "src/random.h",
    ],
    deps = [
    ]
)